### ISSUE TITLE
Feature request get all entities of device

### ISSUE THREAD

**Issue by guyluz11** [twocolors/node-red-contrib-esphome#13]
I am setting my node-red by creating the JSON with code and importing it to node-red.

Currently there is no way for me to get all the entity's id and types, it is not saved on ESPHome device node and there isn't any node that can retrieve the list of entities for a specific device.

I would love to see all of the available entities' data saved under the device node including all the available data for each entity (name, type, id, pin?, platform?, output?).

**Comment by ondonadas** [comment]
@guyluz11 I'm not involved in any way in this project, but I'm my case I can retrieve all entities from esphome on node red, as long as I use API>password instead of API>key

**Comment by guyluz11** [comment]
> 

Interesting, can you give an example?
Not sure that I understand how you did it.

**Comment by ondonadas** [comment]
@guyluz11 yes not sure if you mean the same. I refer to discover and get esphome devices entities inside node red dashboard. Later I'll share some images of you need it

**Comment by ondonadas** [comment]
Please take a look at the image.
As you can see "entity" shows the components I've defined in esphome, but
it only works as long as I declare api > password field in my device.yaml.
[image: Screenshot from 2023-03-12 21-05-11.png]

**Comment by ondonadas** [comment]
@guyluz11 take a look to the image. As you can see entity shows the components I've declared in esphome. It only works as long as you declare api>password inside your device yaml file.

![Screenshot from 2023-03-12 21-05-11](https://user-images.githubusercontent.com/1852881/224571245-32dc5554-ceb6-4aad-ab42-51971c4682eb.png)

**Comment by guyluz11** [comment]
I have managed to configure espHome api nod but without password.

The entities of this device is the next step and I saw that there is a NodeRed network request that I can use for that

**Comment by guyluz11** [comment]
I foud 2 post request that that can be called on node red to get some  results


post(
      Uri.parse('http://localhost:1880/esphome/discovery'),
      encoding: Encoding.getByName('utf-8'),
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: {
        // 'deviceNode': '33621aa0c7804ab0',
      },
    );
To get all entities of a device by esphome device node ide

```dart
post(
      Uri.parse('http://localhost:1880/esphome/entities'),
      encoding: Encoding.getByName('utf-8'),
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: {
        'deviceNode': espHomeDeviceId,
      },
```

**Comment by guyluz11** [comment]
Found with the help from the discord server that I can use the API and include password in the request using 

```
 {
      "id": "$id",
      "type": "$type",
      "name": "$name",
      "target": "",
      "host": "$host",
      "port": "6053",
      "credentials": {
            "password": "$password"
      }
    }
```

**Comment by guyluz11** [comment]
So I have everything that I need in order to discover and create devices with entities from my code.

Thanks

**Comment by twocolors** [comment]
@guyluz11 oh, oh, oh it's okey!

if you won, you can make pull for example like https://github.com/twocolors/node-red-contrib-esphome/blob/main/examples/SwitchOFForON.json
