### ISSUE TITLE
Cant get value to espout-Node for Servo vontrol

### ISSUE THREAD

**Issue by Faeslich8** [twocolors/node-red-contrib-esphome#25]
Hello! 

First of all: great project!

I try to controll a servo with the espout-Node but cant find a way to inject the value correct.

If i try a inject node with number as a payload the servo gets always the position 0. 
![grafik](https://github.com/twocolors/node-red-contrib-esphome/assets/151518339/55e97e0a-dcea-4d85-9c2b-cb937bc7f025)

I tried to inject it as JSON value and wasnt more sucssesfull. Can you tell me what Im doing wrong? 
![grafik](https://github.com/twocolors/node-red-contrib-esphome/assets/151518339/a5bcebc0-b58a-4e24-9e2d-d532607ae53b)

When I`m using the Home Assistent Dashboard I can move the servo fine. 

![grafik](https://github.com/twocolors/node-red-contrib-esphome/assets/151518339/d247421c-d639-416a-b24c-79d0e66ae96e)

Thank und and greetings!

**Comment by twocolors** [comment]
Show me you screen in out-node

**Comment by Faeslich8** [comment]
Thank you for the fast reply,

This is the out-node:
![grafik](https://github.com/twocolors/node-red-contrib-esphome/assets/151518339/3d25e0f0-6c99-4f3f-9c77-bdc3db82236e)

This is the YAML of the servo:
![grafik](https://github.com/twocolors/node-red-contrib-esphome/assets/151518339/a285333f-350f-460f-89f9-981effee7e5c)

**Comment by twocolors** [comment]
try
```
msg.payload.state = 100
```

**Comment by Faeslich8** [comment]
You are a god among men! It works fine now. Thank you very much.
