### ISSUE TITLE
Suppress `connect EHOSTUNREACH xxx.xxx.xxx.xxx:6053`

### ISSUE THREAD

**Issue by caitken-com** [twocolors/node-red-contrib-esphome#29]
Are you able to add a checkbox to suppress connection errors per config node. These spam the debug window when they can't connect which makes it very hard to debug other projects via the debug window.
![Screenshot 2023-12-18 at 9 48 26 pm](https://github.com/twocolors/node-red-contrib-esphome/assets/40314295/48ef938b-7b61-49c3-ad55-c0b1d94e8a4d)

**Comment by twocolors** [comment]
I think this is a bad idea, it would be better to add a value **reconnectInterval** for config device

**Comment by twocolors** [comment]
try node-red-contrib-esphome@0.2.5 and use reconnect

**Comment by y8s** [comment]
I came here looking for this same situation. I have a few devices that are "in test" and I often leave them unconnected for long periods. All this does is fill up debug when I have a device deliberately offline. 

Why not have the node just output a message every connect interval with the connection status? 

None of my other iot/smart device nodes do this when they're offline. Most just report their LWT and show up as offline and vanish.

**Comment by twocolors** [comment]
you can disable node in config sections

**Comment by y8s** [comment]
> you can disable node in config sections

If I disalbe the node, then when the device comes back online it won't work anymore. Is there another disable option you are referring to?
