### ISSUE TITLE
"Connected" status message overrides latest status

### ISSUE THREAD

**Issue by Kilill** [twocolors/node-red-contrib-esphome#30]
When new events/values arrives. the status indicator at the bottom of the node is always overwritten with the  **Connected**  status string thereby losing the latest actual sensor value.

**Comment by twocolors** [comment]
everything is correct, as intended. the value you see is 5 sec

**Comment by Kilill** [comment]
You mean the latest status is supposed to hang around for 5 sec ? that does not seem to be the case though. And if so is there a way for the timeout to be extended or altogether disabled ?

**Comment by twocolors** [comment]
hm , i think status for me work well , this functional work from first releas and chenge some not good idea. 
must ask from people https://discord.gg/uvYac5u , channel esp

**Comment by twocolors** [comment]
try node-red-contrib-esphome@0.2.5

**Comment by Kilill** [comment]
Ah! thanks a lot! that works so much better for me
