### ISSUE TITLE
Node change nothing on HA or ESP

### ISSUE THREAD

**Issue by ThorPrez** [twocolors/node-red-contrib-esphome#35]
I´m giving a set value of 0-100 for fan control (speedlevel; 100) to the input and nothing happens on HA.
The feedback of the input is the last value on HA.
If I´m changing set value in HA the input is giving the right feedback.
The output of ESP is only changing when I´m setting anything on HA, but not in Node-Red.

Seems to be a problem with write protection.

With kind regards,
Thorsten

**Comment by twocolors** [comment]
hi , i not use HA and not can repeat this, if you use HA mb try **node-red-contrib-home-assistant-websocket**

**Comment by ThorPrez** [comment]
Hi.
I´m actually using the websocket because ESP addon is not working. Wanted to send signals directly to the ESP and not with HA between. 
I cannot disable the entity, because than I cannot read it.

**Comment by ThorPrez** [comment]
With the current ESPHome version 2024.10.0 pwm control is not working anymore.
You can set a value, but nothing´s changing on ESP8266.
If I´m using HA to set a value it´s working. When testing I recognized, that Node-Red is using the last value, not the current value I´m sending.
Example: I´m setting 20% in HA and the output is 20%. I´m sending 40% in Node-Redand the output is still 20%.
