### ISSUE TITLE
the node is running normally and working, but there are warning prompts

### ISSUE THREAD

**Issue by iso-lib** [twocolors/node-red-contrib-esphome#36]
![image](https://github.com/twocolors/node-red-contrib-esphome/assets/77186879/08f574fd-0cca-4f8b-becf-d25358b274c7)

**Comment by twocolors** [comment]
you only send "true" ?

**Comment by twocolors** [comment]
try last git version

**Comment by chibm** [comment]
> you only send "true" ? hoh, i repeat this bug if you send **true** in **msg.payload**
> 
> you must use **msg.payload.state**


“Button inputs may be triggered with any payload in the input message. Simply send a timestamp, true, or other payload to the button node. Button type nodes provide no messages into Node-RED.”

**Comment by twocolors** [comment]
try node-red-contrib-esphome@0.2.7
