### ISSUE TITLE
all sensor one message

### ISSUE THREAD

**Issue by bluebier** [twocolors/node-red-contrib-esphome#40]
There is a 16-channel binary sensor device.
I would need all the channels in one message at once.
example:
a1: true
a2:false
a3:false

**Comment by twocolors** [comment]
state from all relay read when connect to esp, when some relay change state, esphome send event only for this relay

if you want one json, i recommend use context in Node-RED (write all state to context, when change update json context for this element)

yep, you will have 16 node IN add all move to one function node

**Comment by bluebier** [comment]
where to activate this function because I can't find it

**Comment by twocolors** [comment]
you must write this function in **node - function**

**Comment by PaulWieland** [comment]
You can probably use the native `Join` node to do this:

<img width="841" alt="Image" src="https://github.com/user-attachments/assets/78dd5da7-6dbb-4303-a4fd-8f70aceb8b90" />

There are several approaches you can take. I would use a change node to set a unique topic for each sensor, and then use the join node to create a combined object after `X` messages, or `X` seconds.
