### ISSUE TITLE
"Status" output not reporting status (there is a workaround)

### ISSUE THREAD

**Issue by DeeBeeKay** [twocolors/node-red-contrib-esphome#41]
Hi @twocolors

Please remember I am willing to help with docs; I don't know how to reach you privately.

This is not a problem, I am simply reporting it.

When I use the ESP-IN node, the Status output does not send any message. That is OK, because I can still subscribe to the actual switches for their status, so my flows still work 100%. But if that output is supposed to send status data on _everything_, it's not working yet.

Thank you for your continued work on this project.

**Comment by twocolors** [comment]
```

**Comment by DeeBeeKay** [comment]
![status](https://github.com/twocolors/node-red-contrib-esphome/assets/48854355/5e97c794-3b7f-4695-8b39-e9c017a68a34)

So, here I am using the ESPHome In node to get information about device status.

If I choose the last option (system - status), there is no data - nothing comes out.

To get status of switches, I have to select the switch itself.

Maybe I don't understand what Status is for.

**Comment by twocolors** [comment]
yep, system - status is send any event when connect or disconnect node-red to esphome (this is status of connection for device)

![image](https://github.com/twocolors/node-red-contrib-esphome/assets/207796/148f4581-91c2-4ede-8caf-c37c85a2b6fd)

system - status is set when change or fist connect, if you add after connect devie you must restart flow/full deploy (Node-Red) or reboot device and system - status will be read or wait when reboot device :)

**Comment by PaulWieland** [comment]
FYI there is a status in node in NR which can be used to trigger a flow based on another node's status changing:

<img width="455" alt="Image" src="https://github.com/user-attachments/assets/448f6277-cf8c-4296-8ed0-ea73529096df" />
