### ISSUE TITLE
Adding new device manually

### ISSUE THREAD

**Issue by guyluz11** [twocolors/node-red-contrib-esphome#6]
Feature request:
I would like to add my espHome devices manually by IP or by mDNS name.

Currently I saw that users can add a new device only if it found the device on the network.

![Screenshot_20230208_081550_Firefox](https://user-images.githubusercontent.com/9304740/217450308-c867604d-40b7-430c-988c-a5f7ba7845bc.jpg)

**Comment by twocolors** [comment]
when you click "pencil" you can add manual host

![image](https://user-images.githubusercontent.com/207796/217484016-ec4d87f7-c6c6-4385-b05b-cb59c6a04fad.png)

**Comment by guyluz11** [comment]
Thanks, I didn't see that as the Node-RED phone ui is not the best.
